<img style="float: left; margin: 30px 15px 15px 15px;" src="https://pngimage.net/wp-content/uploads/2018/06/logo-iteso-png-5.png" width="300" height="500" /> 
    
    
### <font color='navy'> Simulación de procesos financieros. 

**Nombres:** Mariela López Molina - Gilberto Alan Trillo Rendon.

**Fecha:** 09 de Junio de 2021.

**Expediente** : if721862 - if713152 .
**Profesor:** Oscar David Jaramillo Zuluaga.
    
**Link Github**: https://github.com/Mariela07/ProyectoConjunto_MMLopez_GATrillo

# Tarea 3: Clase 6

### Ejercicio 1: Resolver la siguiente ecuación recursiva usando funciones como se vió en clase
$$ D_{n}=(n-1) D_{n-1}+(n-1) D_{n-2} \quad n\ge 3$$
con $D_1=0$ y $D_2 = 1$

Código de solución Mariela

In [27]:
import numpy as np

D1 = 0
D2 = 1

def solucion(n):
    D = np.zeros(n)
    D[0] = D1
    D[1] = D2
    
    def llenar_vector(i):
        nonlocal D
        
        D[i + 2] = (i + 2) * D[i + 1] + (i + 2) * D[i]
        
    [llenar_vector(i) for i in range(n - 2)]
    
    return D

solucion(5)

array([ 0.,  1.,  2.,  9., 44.])

Código de solución Alan

# Ecuación equivalente
$$ D_{n}=(n-1)( D_{n-1}+ D_{n-2} )\quad n\ge 3$$

In [185]:
#Dada la resticción de n => 3, lleno el vector desde el inicio en la posición 0 y 1 los valores de 0 y 1
#y n es el número de resultados que queremos obtener 
import numpy as np
n = 10
x0 = 0
x1 = 1
def sol_eqn():
    D = np.zeros(n)
    D[1] = x0
    D[2] = x1
    def llenar_vect(i):
        nonlocal D
        #Saco el (n-1) para simplificar la ecuación 
        D[i + 3] = ((i + 3) - 1) * (D[(i + 3) - 1] +  D[(i + 3) - 2] )
        
    [llenar_vect(i) for i in range(n - 3) ]
    return D
    
    
sol_eqn()
        
    

array([0.00000e+00, 0.00000e+00, 1.00000e+00, 2.00000e+00, 9.00000e+00,
       4.40000e+01, 2.65000e+02, 1.85400e+03, 1.48330e+04, 1.33496e+05])

### Ejercicio 2: Count the number of spaces in the following string
`variable =  relaciónn  requiere,  para obtener  el  valor  de un  cierto  término,  el conocimiento de los dos anteriores`.

Código de solución Mariela

In [5]:
variable = 'relaciónn  requiere,  para obtener  el  valor  de un  cierto  término,  el conocimiento de los dos anteriores'
espacios = [esp for esp in variable if esp == " "]
print('El número de espacios en la variable es: ', len(espacios))

El número de espacios en la variable es:  23


Código de solución Alan

In [186]:
variable =  "relaciónn  requiere,  para obtener  el  valor  de un  cierto  término,  el conocimiento de los dos anteriores"
print("El número de espacios en esta frase es de (incluye espaciados dobles):", variable.count(" "))

El número de espacios en esta frase es de (incluye espaciados dobles): 23


### Ejercicio 3: Remove all of the vowels in a string [make a list of the non-vowels].

Código de solución Mariela

In [7]:
def remove_vowels(variable):
    vowels = 'aeiouáéíóú'
    e = ""
    return e.join([x for x in variable if x not in vowels])

variable = 'relaciónn  requiere,  para obtener  el  valor  de un  cierto  término,  el conocimiento de los dos anteriores'
newstring = remove_vowels(variable)
newstring

'rlcnn  rqr,  pr btnr  l  vlr  d n  crt  trmn,  l cncmnt d ls ds ntrrs'

Código de solución Alan

In [50]:
#Esta función nos ayuda a quitar elemntos de un texto, es el primer argumento, después ponemo el sustituto, la variable
#(en este caso yo lo hago en una función), y le pedimos que ignore el lugar o elimine en donde estaba el primer argumento
re?

In [187]:
import re


def non_vowels(x):
    non_vow = re.sub(r'[AEIOU]','',x, flags=re.IGNORECASE)
    return non_vow
non_vowels(variable)
    

'rlcónn  rqr,  pr btnr  l  vlr  d n  crt  térmn,  l cncmnt d ls ds ntrrs'

### Ejercicio 4: Find all of the words in a string that are less than 4 letters.

Código de solución Mariela

In [8]:
variable = 'relaciónn  requiere,  para obtener  el  valor  de un  cierto  término,  el conocimiento de los dos anteriores'

list(filter(lambda word: len(word) < 4 , variable.split()))

['el', 'de', 'un', 'el', 'de', 'los', 'dos']

Código de solución Alan

In [188]:
#Hice un for clásico, ya agendé asesoría, me confundo con el if al momento de hacer map
result = []
for i in range (len(var_new)):
    if len(var_new[i]) >= 4: 
        result.append(var_new[i])
result

['relaciónn',
 'requiere,',
 'para',
 'obtener',
 'valor',
 'cierto',
 'término,',
 'conocimiento',
 'anteriores']

### Ejercicio 5: Use a dictionary comprehension to count the length of each word in a sentence.

Código de solución Mariela

In [9]:
variable = 'relaciónn  requiere,  para obtener  el  valor  de un  cierto  término,  el conocimiento de los dos anteriores'

list(map(len, variable.split()))

[9, 9, 4, 7, 2, 5, 2, 2, 6, 8, 2, 12, 2, 3, 3, 10]

Código de solución Alan

In [176]:
var_new = variable.split()
word_lenght = [len(var_new[i]) for i in range(len(var_new))]
word_lenght

[9, 9, 4, 7, 2, 5, 2, 2, 6, 8, 2, 12, 2, 3, 3, 10]

### Ejercicio 6: Use a nested list comprehension to find all of the numbers from 1-1000 that are divisible by any single digit besides 1 (2-9). 

Código de solución Mariela

In [14]:
numbers = np.array([number for number in range(1, 1001) if [True for divisor in range(2,10) if number % divisor == 0]])
numbers

array([   2,    3,    4,    5,    6,    7,    8,    9,   10,   12,   14,
         15,   16,   18,   20,   21,   22,   24,   25,   26,   27,   28,
         30,   32,   33,   34,   35,   36,   38,   39,   40,   42,   44,
         45,   46,   48,   49,   50,   51,   52,   54,   55,   56,   57,
         58,   60,   62,   63,   64,   65,   66,   68,   69,   70,   72,
         74,   75,   76,   77,   78,   80,   81,   82,   84,   85,   86,
         87,   88,   90,   91,   92,   93,   94,   95,   96,   98,   99,
        100,  102,  104,  105,  106,  108,  110,  111,  112,  114,  115,
        116,  117,  118,  119,  120,  122,  123,  124,  125,  126,  128,
        129,  130,  132,  133,  134,  135,  136,  138,  140,  141,  142,
        144,  145,  146,  147,  148,  150,  152,  153,  154,  155,  156,
        158,  159,  160,  161,  162,  164,  165,  166,  168,  170,  171,
        172,  174,  175,  176,  177,  178,  180,  182,  183,  184,  185,
        186,  188,  189,  190,  192,  194,  195,  1

Código de solución Alan

In [190]:
#def fun(x, y):
#    x%y
#resul = list(map(lambda i: list(map(lambda j: j(i), fun))))



In [191]:
#Hice un for clásico, ya agendé asesoría, me confundo con el if al momento de hacer map
resultado = []
for i in range(2,9):
    for j in range(1,1000):
        if j%i: resultado.append(j) 
resultado

[1,
 3,
 5,
 7,
 9,
 11,
 13,
 15,
 17,
 19,
 21,
 23,
 25,
 27,
 29,
 31,
 33,
 35,
 37,
 39,
 41,
 43,
 45,
 47,
 49,
 51,
 53,
 55,
 57,
 59,
 61,
 63,
 65,
 67,
 69,
 71,
 73,
 75,
 77,
 79,
 81,
 83,
 85,
 87,
 89,
 91,
 93,
 95,
 97,
 99,
 101,
 103,
 105,
 107,
 109,
 111,
 113,
 115,
 117,
 119,
 121,
 123,
 125,
 127,
 129,
 131,
 133,
 135,
 137,
 139,
 141,
 143,
 145,
 147,
 149,
 151,
 153,
 155,
 157,
 159,
 161,
 163,
 165,
 167,
 169,
 171,
 173,
 175,
 177,
 179,
 181,
 183,
 185,
 187,
 189,
 191,
 193,
 195,
 197,
 199,
 201,
 203,
 205,
 207,
 209,
 211,
 213,
 215,
 217,
 219,
 221,
 223,
 225,
 227,
 229,
 231,
 233,
 235,
 237,
 239,
 241,
 243,
 245,
 247,
 249,
 251,
 253,
 255,
 257,
 259,
 261,
 263,
 265,
 267,
 269,
 271,
 273,
 275,
 277,
 279,
 281,
 283,
 285,
 287,
 289,
 291,
 293,
 295,
 297,
 299,
 301,
 303,
 305,
 307,
 309,
 311,
 313,
 315,
 317,
 319,
 321,
 323,
 325,
 327,
 329,
 331,
 333,
 335,
 337,
 339,
 341,
 343,
 345,
 347,
 349,
 351,